swagger: '2.0'
info:
  title: FP550 Printer API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
# security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  # - oauth2: [uid]
paths:
  /:
    get:
      tags:
        - Home Page
      summary: Displays static page.
      description: Displays the index html page
      operationId: app.go_home
      produces:
        - text/html
      responses:
        '200':
          description: Successfully loaded html page.
          schema:
            type: string
          examples:
            "text/plain": "Hello John"

  /g1:
    get:
      tags: [G1_Commands]
      summary: G1 Commands
      description: Generic command
      operationId: app.g1_cmd
      parameters:
        - name: cmd
          description: Command ID. 1-Date_Time, 2-PIB, 3-Paper_Move, 4-Status, 5-Get_Tax, 6-Diag, 7-Report_Art_All, 8-Get_Set_Tax
          in: query
          type: integer
          required: true
        - name: data
          description: Command data. Default "" - Empty String
          in: query
          type: string
          default: ""
          required: false
      responses:
        '200':
          description: Response object
          schema:
            type: object
          examples:
            "LEN": pck_Len
            "SEQ": pck_Seq
            "Cmd": pck_Cmd
            "Status": pck_Sts
            "recv_pck_Data": pck_Data

  /g21_cmd:
    get:
      summary: G21 command-Take usb camera photo
      tags: [G2_Commands]
      operationId: app.g21_cmd
      description: Take a photo by usb camera and return link to timestamped .jpg.

      responses:
        200:
          description: link to usb photo .jpg
          schema:
            type: string

  /g31:
    post:
      tags: [G3_Commands]
      summary: G3.1 Print Non-Fiscal
      description: Prints non-fiscal for entered string
      operationId: app.g31_cmd
      parameters:
        - name: data
          description: String that needs to be printed
          in: query
          type: string
          required: true
      responses:
        '200':
          description: Print result
          schema:
            type: string

  /g32:
    post:
      tags: [G3_Commands]
      summary: G3.2 Print Fiscal
      description: Prints fiscal for entered string
      operationId: app.g32_cmd
      parameters:
        - name: data
          description: <PLU>,<Quantity>,<Price>/...
          in: query
          type: string
          required: true
      responses:
        '200':
          description: Print result
          schema:
            type: string



  /g33:
    post:
      tags: [G3_Commands]
      summary: G3.3 Write Article
      description: Adds article to database
      operationId: app.g33_cmd
      parameters:
        - name: plu
          description: PLU 100+
          in: query
          type: integer
          required: true
        - name: price
          description: Price
          in: query
          type: integer
          required: true
        - name: name
          description: Name
          in: query
          type: string
          required: true
      responses:
        '200':
          description: Output
          schema:
            type: string

  /g34:
    post:
      tags: [G3_Commands]
      summary: G3.4 Read All Articles
      description: Outputs all articles
      operationId: app.g34_cmd
      responses:
        '200':
          description: List of articles
          schema:
            type: string

  /hw_proxy/hello:
    get:
      summary: hello-ping for POS
      tags: [POS_BOX]
      operationId: app.hello
      description: PING response to the POS request

      responses:
        200:
          description: ping
          schema:
            type: string
  /hw_proxy/handshake:
    post:
      summary: handshake for POS
      tags: [POS_BOX]
      operationId: app.handshake_json
      description: handshake response to the POS request

      responses:
        200:
          description: potvrda
          schema:
            type: boolean
  /hw_proxy/status_json:
    post:
      summary: Status EscPOS drivera
      tags: [POS_BOX]
      operationId: app.status_json
      description: Status with escpos printer connected response to the POS request

      responses:
        200:
          description: escpos connected
          schema:
            type: object
  /hw_proxy/print_xml_receipt:
    post:
      summary: print XML-HTML receipt
      tags: [POS_BOX]
      operationId: app.print_xml_receipt_json
      description: Print to the escpos printer  POS receipt

      responses:
        200:
          description: escpos connected
          schema:
            type: object

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
