swagger: '2.0'
info:
  title: FP550 Printer API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
# security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  # - oauth2: [uid]
paths:
  /:
    get:
      tags:
        - Home Page
      summary: Displays static page.
      description: Displays the index html page
      operationId: app.go_home
      produces:
        - text/html
      responses:
        '200':
          description: Successfully loaded html page.
          schema:
            type: string
          examples:
            "text/plain": "Hello John"

  /g1:
    get:
      tags: [G1_Commands]
      summary: G1 Commands
      description: Generic command
      operationId: app.g1_cmd
      parameters:
        - name: cmd
          description: Command ID. 1-Date_Time, 2-PIB, 3-Paper_Move, 4-Status, 5-Get_Tax, 6-Diag, 7-Report_Art_All, 8-Get_Set_Tax
          in: query
          type: integer
          required: true
        - name: data
          description: Command data. Required for cmd-3, default 0.
          in: query
          type: string
          default: ""
          required: false
      responses:
        '200':
          description: Response object
          schema:
            type: object
          examples:
            "LEN": pck_Len
            "SEQ": pck_Seq
            "Cmd": pck_Cmd
            "Status": pck_Sts
            "recv_pck_Data": pck_Data

  /g21_cmd:
    get:
      summary: G21 command-Take usb camera photo
      tags: [G2_Commands]
      operationId: app.g21_cmd
      description: Take a photo by usb camera and return link to timestamped .jpg.

      responses:
        200:
          description: link to usb photo .jpg
          schema:
            type: string


securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
